apiVersion: apps/v1
kind: Deployment
metadata:
  name: podchaosmonkey
  namespace: choasmonkey
  labels:
    app: podchaosmonkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podchaosmonkey
  template:
    metadata:
      labels:
        app: podchaosmonkey
    spec:
      serviceAccountName: podchaosmonkey
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - name: podchaosmonkey
        image: podchaosmonkey # update to include registry and tag
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podchaosmonkey
  namespace: choasmonkey
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podchaosmonkey
  namespace: choasmonkey
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podchaosmonkey
  namespace: choasmonkey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podchaosmonkey
subjects:
- kind: ServiceAccount
  name: podchaosmonkey
  namespace: choasmonkey
---
apiVersion: v1
kind: Namespace
metadata:
  name: choasmonkey